
name: 'Configure Git Credentials'
description: 'Configure Git credentials for accessing private repositories'
inputs:
  token:
    description: 'GitHub token for authentication'
    required: true
runs:
  using: "composite"
  steps:
    - name: Configure Git credentials
      shell: bash
      run: |
        if [ -z "${{ inputs.token }}" ]; then
          echo "❌ EVM_VERIFIER_EZKL_TOKEN is empty – check repo/org secrets" >&2
          exit 1
        fi
        
        # For libgit2 (what Cargo uses internally)
        git config --global credential.helper store
        echo "https://oauth2:${{ inputs.token }}@github.com" > ~/.git-credentials
        chmod 600 ~/.git-credentials
        
        # Also set URL replacement with oauth2 format
        git config --global \
          url."https://oauth2:${{ inputs.token }}@github.com/".insteadOf \
          "https://github.com/"